package com.ueueo.datagenerator.core;

/**
 * An abstracts class to be extended by classes that will generate data items
 * from an array of values of type <code>T</code>
 * 
 * @author Agustin Barto <abarto@gmail.com>
 *
 * @param <T> Type of data items that will be generated by the classes that
 * extends this one. 
 */
public abstract class ArrayBasedGeneratorBase<T> {
	/**
	 * The values that will be used to generate data items.
	 */
	protected T[] values;

	/**
	 * Constructor.
	 * 
	 * @param values An array of values from which to extract the data items.
	 */
	public ArrayBasedGeneratorBase(T... values) {
		this.values = values;
	}
}
